- content: "国家自然科学基金重点项目，“Group actions, symmetric graphs and symmetric geometries”，2020.01 – 2024.12，参与（1/8）。"
- content: "国家重点研发计划子项目，科技部，“Paradigms of artificial intelligence algorithms”，2017.10 – 2020.09，子项目主持。"      
- content: "国家自然科学基金面上项目，“Algebraic manipulation detection codes and their applications”，2017.01 – 2020.12，主持。"
- content: "国家自然科学基金青年科学计划，“The combinatorial properties of the preimage sets and image sets of nonlinear functions”，2017.01 – 2019.12，主持。"

    